### PR TITLE
Edit-Distance.c

### PR DESCRIPTION
**Pull request by Mkishore7**
Given two strings str1 and str2 and below operations that can be performed on str1. Find the minimum number of edits (operations) required to convert ‘str1’ into ‘str2’.
Test case :
Input:
sunday
saturday 
Output:  3
Last three and first characters are same.  We basically
need to convert "un" to "atur".  This can be done using
below three operations. 
Replace 'n' with 'r', insert t, insert a

### CODE REVIEW

**Comment by codeShaurya** [comment]
I have noticed a certain thing
1.  example should at the end of the file and out of function body
2. spacing is not in an ordered manner 
    eg.   function() 
                           {
                  // this is the wrong way
            }

            //right way
           function() {
                      // this is the right method
            }
3. opening "{" braces will be at the end of the function definition line, not in the new line

**Review by Mkishore7 — COMMENTED** [review]
Considered the suggestions and made suitable changes to the code.

**Comment by Mkishore7** [comment]
Understood. I made suitable changes to the code as per my understanding.

**Comment by codeShaurya** [comment]
I have made all the changes. You can go through it.

**Pull request merged**
